# Generated by Django 5.0.1 on 2024-01-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(default='DNI no establecido', max_length=100)),
                ('metodo_pago', models.CharField(default='Metodo de pago no establecido', max_length=100)),
                ('fecha_de_entrada', models.CharField(default='Fecha de entrada no establecida', max_length=100)),
                ('numero_telefono', models.CharField(default='Telefono no establecido', max_length=100)),
            ],
        ),
    ]
