# Generated by Django 5.0.1 on 2024-01-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dias_abonados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_de_entrada',
            field=models.DateField(default='0-0-0'),
        ),
    ]
