# Generated by Django 5.0.1 on 2024-01-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_dias_abonados_alter_user_fecha_de_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(default='Direccion no establecida', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre_completo',
            field=models.CharField(default='Nombre no establecido', max_length=255),
        ),
    ]
